// M2.1 —— 开发/测试期幂等建表（与 drizzle-kit 生成的迁移脚本等价）
// 生产环境请用 migrations/ 下的标准 Postgres 迁移（drizzle-kit migrate 或 psql -f）。
// P1 zone 化：个人域表统一加 owner_id / visibility / version / last_edited_by；
//   family_idx 改为复合 (owner_id, visibility)，并加 version 单列索引；calendar_events.version 改为 integer。
//   family_id 列保留（双写过渡期）。
import { sql } from 'drizzle-orm';
import { ensureSystemAuthor, ensureSystemFamily } from './systemAuthor';

const DDL = [
  `CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    name text NOT NULL,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS families (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    owner_id uuid NOT NULL REFERENCES users(id),
    kind text NOT NULL DEFAULT 'personal',
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS memberships (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role text NOT NULL,
    joined_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (family_id, user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS invitations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    token text NOT NULL UNIQUE,
    role text NOT NULL,
    created_by uuid NOT NULL REFERENCES users(id),
    expires_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS calendar_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    location text,
    start_at timestamptz NOT NULL,
    end_at timestamptz,
    all_day boolean NOT NULL DEFAULT false,
    created_by uuid NOT NULL REFERENCES users(id),
    version integer NOT NULL DEFAULT 1,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    last_edited_by uuid REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS memberships_family_idx ON memberships(family_id)`,
  `CREATE INDEX IF NOT EXISTS memberships_user_idx ON memberships(user_id)`,
  `CREATE INDEX IF NOT EXISTS invitations_family_idx ON invitations(family_id)`,
  `CREATE INDEX IF NOT EXISTS sessions_refresh_idx ON sessions(refresh_token)`,
  `CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id)`,
  `CREATE INDEX IF NOT EXISTS calendar_events_family_idx ON calendar_events(family_id)`,
  `CREATE INDEX IF NOT EXISTS calendar_events_zone_idx ON calendar_events(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS calendar_events_version_idx ON calendar_events(version)`,
  `CREATE INDEX IF NOT EXISTS calendar_events_start_idx ON calendar_events(family_id, start_at)`,
  `CREATE INDEX IF NOT EXISTS calendar_events_family_vis_idx ON calendar_events(family_id, visibility)`,
  `CREATE TABLE IF NOT EXISTS shared_finance_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_type text NOT NULL,
    item_key text NOT NULL,
    label text NOT NULL,
    scope text NOT NULL DEFAULT 'all',
    allowed_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    snapshot jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS sfi_family_idx ON shared_finance_items(family_id)`,
  `CREATE INDEX IF NOT EXISTS sfi_owner_idx ON shared_finance_items(family_id, owner_user_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS sfi_owner_item_uniq ON shared_finance_items(family_id, owner_user_id, item_type, item_key)`,
  `CREATE TABLE IF NOT EXISTS shared_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    module text NOT NULL,
    item_type text NOT NULL,
    item_key text NOT NULL,
    label text NOT NULL,
    scope text NOT NULL DEFAULT 'all',
    allowed_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    snapshot jsonb NOT NULL,
    done boolean NOT NULL DEFAULT false,
    note text,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS si_family_idx ON shared_items(family_id)`,
  `CREATE INDEX IF NOT EXISTS si_owner_idx ON shared_items(family_id, owner_user_id)`,
  `CREATE INDEX IF NOT EXISTS si_module_idx ON shared_items(family_id, module)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS si_owner_item_uniq ON shared_items(family_id, owner_user_id, module, item_type, item_key)`,
  `CREATE TABLE IF NOT EXISTS domains (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    key text NOT NULL,
    name text NOT NULL,
    is_quarter_focus boolean NOT NULL DEFAULT false,
    color text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS domains_family_key_uniq ON domains(family_id, key)`,
  `CREATE INDEX IF NOT EXISTS domains_family_idx ON domains(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS domains_version_idx ON domains(version)`,
  `CREATE TABLE IF NOT EXISTS projects (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    name text NOT NULL,
    para_type text NOT NULL DEFAULT 'project',
    goal_id text,
    status text NOT NULL DEFAULT 'active',
    pdca_state text,
    created_at text NOT NULL,
    archived_at text
  )`,
  `CREATE INDEX IF NOT EXISTS projects_family_idx ON projects(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS projects_version_idx ON projects(version)`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    title text NOT NULL,
    domain_key text NOT NULL,
    project_id text,
    importance boolean NOT NULL DEFAULT false,
    urgency boolean NOT NULL DEFAULT false,
    is_mit boolean NOT NULL DEFAULT false,
    mit_order integer,
    status text NOT NULL DEFAULT 'todo',
    scheduled_start text,
    scheduled_end text,
    due_at text,
    description text NOT NULL DEFAULT '',
    priority text NOT NULL DEFAULT 'medium',
    created_at text NOT NULL,
    completed_at text,
    completion_quality integer,
    attention_peak integer,
    task_date text,
    repeat text NOT NULL DEFAULT 'none',
    source_daily_id text,
    updated_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS tasks_family_idx ON tasks(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS tasks_version_idx ON tasks(version)`,
  `CREATE INDEX IF NOT EXISTS tasks_domain_idx ON tasks(owner_id, visibility, domain_key, status)`,
  `CREATE INDEX IF NOT EXISTS tasks_mit_idx ON tasks(owner_id, visibility, is_mit, mit_order)`,
  `CREATE INDEX IF NOT EXISTS tasks_due_idx ON tasks(owner_id, visibility, due_at)`,
  `CREATE INDEX IF NOT EXISTS tasks_date_idx ON tasks(owner_id, visibility, task_date)`,
  `CREATE INDEX IF NOT EXISTS tasks_daily_idx ON tasks(owner_id, visibility, source_daily_id, task_date)`,
  `CREATE TABLE IF NOT EXISTS interests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    title text NOT NULL,
    content text,
    attention integer NOT NULL DEFAULT 1,
    source_type text NOT NULL DEFAULT 'manual',
    source_ref text,
    domain_key text,
    effort_budget text NOT NULL DEFAULT 'tbd',
    status text NOT NULL DEFAULT 'incubating',
    linked_task_id text,
    linked_project_id text,
    view_count integer NOT NULL DEFAULT 0,
    linked_note_count integer NOT NULL DEFAULT 0,
    validated_at text,
    converted_at text,
    archived_at text,
    discarded_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS interests_family_idx ON interests(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS interests_version_idx ON interests(version)`,
  `CREATE INDEX IF NOT EXISTS interests_status_idx ON interests(owner_id, visibility, status)`,
  `CREATE INDEX IF NOT EXISTS interests_domain_idx ON interests(owner_id, visibility, domain_key)`,
  `CREATE TABLE IF NOT EXISTS notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    title text NOT NULL,
    body_markdown text NOT NULL,
    links jsonb NOT NULL DEFAULT '[]'::jsonb,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    kind text NOT NULL DEFAULT 'idea',
    task_id text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    embedded_at text,
    embedding text
  )`,
  `CREATE INDEX IF NOT EXISTS notes_family_idx ON notes(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS notes_version_idx ON notes(version)`,
  `CREATE INDEX IF NOT EXISTS notes_embedded_idx ON notes(owner_id, visibility, embedded_at)`,
  `CREATE INDEX IF NOT EXISTS notes_kind_idx ON notes(owner_id, visibility, kind)`,
  `CREATE TABLE IF NOT EXISTS debts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    creditor text NOT NULL,
    principal numeric(18,2) NOT NULL,
    apr numeric(8,4),
    min_payment numeric(18,2),
    due_day integer,
    status text NOT NULL DEFAULT 'active',
    debt_type text NOT NULL DEFAULT 'other',
    term_months integer,
    repayment_method text NOT NULL DEFAULT 'equal_installment',
    start_date text,
    rate_type text,
    base_rate numeric(8,4),
    rate_spread numeric(8,4),
    rate_adjustments jsonb,
    repricing jsonb,
    prepayments jsonb,
    parent_debt_id text,
    note text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS debts_family_idx ON debts(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS debts_version_idx ON debts(version)`,
  `CREATE INDEX IF NOT EXISTS debts_status_idx ON debts(owner_id, visibility, status)`,
  `CREATE TABLE IF NOT EXISTS incomes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    source text NOT NULL,
    amount numeric(18,2) NOT NULL,
    currency text NOT NULL DEFAULT 'CNY',
    received_at text NOT NULL,
    recurring boolean NOT NULL DEFAULT false,
    note text NOT NULL DEFAULT '',
    income_type text NOT NULL DEFAULT 'salary',
    monthly_avg numeric(18,2),
    is_fixed boolean NOT NULL DEFAULT true,
    income_mode text NOT NULL DEFAULT 'monthly',
    pay_day integer,
    adjustment_day integer,
    rate_adjustments jsonb,
    created_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS incomes_family_idx ON incomes(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS incomes_version_idx ON incomes(version)`,
  `CREATE INDEX IF NOT EXISTS incomes_at_idx ON incomes(owner_id, visibility, received_at)`,
  `CREATE TABLE IF NOT EXISTS transactions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    kind text NOT NULL,
    category text NOT NULL,
    amount numeric(18,2) NOT NULL,
    merchant text,
    occurred_at text NOT NULL,
    note text NOT NULL DEFAULT '',
    debt_id text,
    income_source_id text,
    created_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS transactions_family_idx ON transactions(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS transactions_version_idx ON transactions(version)`,
  `CREATE INDEX IF NOT EXISTS transactions_at_idx ON transactions(owner_id, visibility, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS transactions_kind_idx ON transactions(owner_id, visibility, kind)`,
  `CREATE TABLE IF NOT EXISTS assets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    name text NOT NULL,
    asset_class text NOT NULL,
    value numeric(18,2) NOT NULL,
    as_of text NOT NULL,
    linked_income_source_id text,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS assets_family_idx ON assets(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS assets_version_idx ON assets(version)`,
  `CREATE INDEX IF NOT EXISTS assets_class_idx ON assets(owner_id, visibility, asset_class)`,
  `CREATE TABLE IF NOT EXISTS budgets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    name text NOT NULL,
    scope text NOT NULL DEFAULT 'overall',
    category text,
    monthly_limit numeric(18,2) NOT NULL,
    note text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS budgets_family_idx ON budgets(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS budgets_version_idx ON budgets(version)`,
  `CREATE INDEX IF NOT EXISTS budgets_scope_idx ON budgets(owner_id, visibility, scope)`,
  `CREATE TABLE IF NOT EXISTS reminder_clocks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    title text NOT NULL,
    domain_key text NOT NULL,
    period_rule text NOT NULL,
    lead_chain jsonb NOT NULL DEFAULT '["7","1","0"]'::jsonb,
    note_linked text,
    next_fire_at text NOT NULL,
    last_fired_at text,
    last_completed_at text,
    status text NOT NULL DEFAULT 'active',
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS reminder_fire_idx ON reminder_clocks(owner_id, visibility, next_fire_at, status)`,
  `CREATE INDEX IF NOT EXISTS reminder_next_fire_idx ON reminder_clocks(next_fire_at)`,
  `CREATE INDEX IF NOT EXISTS reminder_version_idx ON reminder_clocks(version)`,
  `CREATE TABLE IF NOT EXISTS focus_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    task_id text,
    domain_key text,
    project_id text,
    attention_type text NOT NULL DEFAULT 'deep',
    started_at text NOT NULL,
    ended_at text NOT NULL,
    score integer,
    energy_start integer,
    energy_end integer,
    interruptions jsonb NOT NULL DEFAULT '[]'::jsonb,
    note text,
    created_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS focus_family_idx ON focus_sessions(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS focus_version_idx ON focus_sessions(version)`,
  `CREATE INDEX IF NOT EXISTS focus_started_idx ON focus_sessions(owner_id, visibility, started_at)`,
  `CREATE INDEX IF NOT EXISTS focus_domain_idx ON focus_sessions(owner_id, visibility, domain_key)`,
  `CREATE INDEX IF NOT EXISTS focus_project_idx ON focus_sessions(owner_id, visibility, project_id)`,
  `CREATE INDEX IF NOT EXISTS focus_task_idx ON focus_sessions(owner_id, visibility, task_id)`,
  `CREATE TABLE IF NOT EXISTS finance_transfers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    from_account_id text NOT NULL,
    to_account_id text NOT NULL,
    amount_minor integer NOT NULL,
    currency text NOT NULL DEFAULT 'CNY',
    occurred_at text NOT NULL,
    note text NOT NULL DEFAULT '',
    idempotency_key text,
    reversed integer NOT NULL DEFAULT 0,
    reversed_at text,
    created_at text NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS transfer_family_idx ON finance_transfers(owner_id, visibility)`,
  `CREATE INDEX IF NOT EXISTS transfer_version_idx ON finance_transfers(version)`,
  `CREATE INDEX IF NOT EXISTS transfer_from_idx ON finance_transfers(owner_id, visibility, from_account_id)`,
  `CREATE INDEX IF NOT EXISTS transfer_to_idx ON finance_transfers(owner_id, visibility, to_account_id)`,
  `CREATE INDEX IF NOT EXISTS transfer_at_idx ON finance_transfers(owner_id, visibility, occurred_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS transfer_idem_uniq ON finance_transfers(family_id, idempotency_key)`,
  `CREATE TABLE IF NOT EXISTS system_meta (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    owner_id uuid NOT NULL REFERENCES users(id),
    visibility text NOT NULL DEFAULT 'private',
    version integer NOT NULL DEFAULT 1,
    last_edited_by uuid REFERENCES users(id),
    key text NOT NULL,
    value jsonb,
    updated_at text NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS system_meta_owner_vis_key_uniq ON system_meta(owner_id, visibility, key)`,
  `CREATE INDEX IF NOT EXISTS system_meta_zone_idx ON system_meta(owner_id, visibility)`,
];

/**
 * 增量列迁移（升级兼容）：已存在的库若是在 `done`/`note` 列加入 schema 之前创建的，
 * `CREATE TABLE IF NOT EXISTS` 会跳过整张表，导致 `shared_items` 缺列，
 * 共享保存报 `column "done" of relation "shared_items" does not exist`。
 * 用幂等的 `ADD COLUMN IF NOT EXISTS` 补齐（PGLite/真 Postgres 通用），每次启动安全重放。
 */
const COLUMN_MIGRATIONS = [
  `ALTER TABLE shared_items ADD COLUMN IF NOT EXISTS done boolean NOT NULL DEFAULT false`,
  `ALTER TABLE shared_items ADD COLUMN IF NOT EXISTS note text`,
  `ALTER TABLE families ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'personal'`,
  `ALTER TABLE debts ALTER COLUMN principal TYPE numeric(18,2) USING principal::numeric(18,2)`,
  `ALTER TABLE debts ALTER COLUMN apr TYPE numeric(8,4) USING apr::numeric(8,4)`,
  `ALTER TABLE debts ALTER COLUMN min_payment TYPE numeric(18,2) USING min_payment::numeric(18,2)`,
  `ALTER TABLE debts ALTER COLUMN base_rate TYPE numeric(8,4) USING base_rate::numeric(8,4)`,
  `ALTER TABLE debts ALTER COLUMN rate_spread TYPE numeric(8,4) USING rate_spread::numeric(8,4)`,
  `ALTER TABLE incomes ALTER COLUMN amount TYPE numeric(18,2) USING amount::numeric(18,2)`,
  `ALTER TABLE incomes ALTER COLUMN monthly_avg TYPE numeric(18,2) USING monthly_avg::numeric(18,2)`,
  `ALTER TABLE transactions ALTER COLUMN amount TYPE numeric(18,2) USING amount::numeric(18,2)`,
  `ALTER TABLE assets ALTER COLUMN value TYPE numeric(18,2) USING value::numeric(18,2)`,
  `ALTER TABLE budgets ALTER COLUMN monthly_limit TYPE numeric(18,2) USING monthly_limit::numeric(18,2)`,
  `DO $$ BEGIN
    IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'calendar_events' AND column_name = 'version') <> 'integer' THEN
      ALTER TABLE calendar_events ALTER COLUMN version TYPE integer USING COALESCE(EXTRACT(EPOCH FROM version), 1)::integer;
    END IF;
  END $$`,
  // P1 zone 化：补齐 tasks 的 zone 四列,
  `ALTER TABLE tasks ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE tasks SET owner_id = (SELECT owner_id FROM families WHERE families.id = tasks.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE tasks ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE tasks ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE tasks ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE tasks ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 notes 的 zone 四列,
  `ALTER TABLE notes ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE notes SET owner_id = (SELECT owner_id FROM families WHERE families.id = notes.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE notes ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE notes ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE notes ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE notes ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 reminder_clocks 的 zone 四列,
  `ALTER TABLE reminder_clocks ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE reminder_clocks SET owner_id = (SELECT owner_id FROM families WHERE families.id = reminder_clocks.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE reminder_clocks ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE reminder_clocks ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE reminder_clocks ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE reminder_clocks ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 debts 的 zone 四列,
  `ALTER TABLE debts ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE debts SET owner_id = (SELECT owner_id FROM families WHERE families.id = debts.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE debts ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE debts ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE debts ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE debts ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 incomes 的 zone 四列,
  `ALTER TABLE incomes ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE incomes SET owner_id = (SELECT owner_id FROM families WHERE families.id = incomes.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE incomes ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE incomes ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE incomes ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE incomes ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 transactions 的 zone 四列,
  `ALTER TABLE transactions ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE transactions SET owner_id = (SELECT owner_id FROM families WHERE families.id = transactions.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE transactions ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE transactions ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE transactions ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE transactions ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 assets 的 zone 四列,
  `ALTER TABLE assets ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE assets SET owner_id = (SELECT owner_id FROM families WHERE families.id = assets.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE assets ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE assets ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE assets ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE assets ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 budgets 的 zone 四列,
  `ALTER TABLE budgets ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE budgets SET owner_id = (SELECT owner_id FROM families WHERE families.id = budgets.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE budgets ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE budgets ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE budgets ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE budgets ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 interests 的 zone 四列,
  `ALTER TABLE interests ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE interests SET owner_id = (SELECT owner_id FROM families WHERE families.id = interests.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE interests ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE interests ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE interests ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE interests ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 projects 的 zone 四列,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE projects SET owner_id = (SELECT owner_id FROM families WHERE families.id = projects.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE projects ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 domains 的 zone 四列,
  `ALTER TABLE domains ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE domains SET owner_id = (SELECT owner_id FROM families WHERE families.id = domains.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE domains ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE domains ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE domains ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE domains ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 focus_sessions 的 zone 四列,
  `ALTER TABLE focus_sessions ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE focus_sessions SET owner_id = (SELECT owner_id FROM families WHERE families.id = focus_sessions.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE focus_sessions ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE focus_sessions ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE focus_sessions ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE focus_sessions ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 finance_transfers 的 zone 四列,
  `ALTER TABLE finance_transfers ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE finance_transfers SET owner_id = (SELECT owner_id FROM families WHERE families.id = finance_transfers.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE finance_transfers ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE finance_transfers ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE finance_transfers ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE finance_transfers ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 system_meta 的 zone 四列,
  `ALTER TABLE system_meta ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE system_meta SET owner_id = (SELECT owner_id FROM families WHERE families.id = system_meta.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE system_meta ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE system_meta ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE system_meta ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE system_meta ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`,
  // P1 zone 化：补齐 calendar_events 的 zone 四列,
  `ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES users(id)`,
  `UPDATE calendar_events SET owner_id = (SELECT owner_id FROM families WHERE families.id = calendar_events.family_id) WHERE owner_id IS NULL`,
  `ALTER TABLE calendar_events ALTER COLUMN owner_id SET NOT NULL`,
  `ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'private'`,
  `ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`,
  `ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS last_edited_by uuid REFERENCES users(id)`
];

/** 在已连接的 PG 兼容数据库上幂等创建全部表与索引（pglite / 真 Postgres 通用） */
export async function ensureSchema(db: any): Promise<void> {
  for (const stmt of DDL) {
    await db.execute(sql.raw(stmt));
  }
  for (const stmt of COLUMN_MIGRATIONS) {
    await db.execute(sql.raw(stmt));
  }
  // P1（v3③）：幂等 upsert 全零系统用户 + 系统家庭，作为 public 行兜底 owner / 改挂 family
  await ensureSystemAuthor(db);
  await ensureSystemFamily(db);
}
